### PR TITLE
Ask people to give DxDiag links to person helping them, instead of just "visit technical support resources

### PR DESCRIPTION
**Pull request by Southpaw1496**
This change was discussed in Discord (requested by Whomsky) and should avoid confusion if the person following the guide is not receiving help from a technical support resource.

### CODE REVIEW

**Comment by LordRalex** [comment]
The issue with the wording is we've gone back and forth on it. The issue then will be users will DM the report to the one who asked, or DM it to Absol because "they asked for it". Either way we will have issues.

**Comment by Southpaw1496** [comment]
I think this wording is good because although Absol asked for it, in most situations they know he's not the one helping them, the human is.

Even if they do DM Absol, that situation is better than the situation this is trying to avoid, which is people receiving the instructions in gg/Minecraft (because the page is linked there) and then coming to MCCS because it's listed in the technical support resources page that the current article tells you to visit after filling out your report.

**Comment by LordRalex** [comment]
Well, the issue is.... users don't realize that. The fact they go to our Discord instead indicates they don't realize what we think they do. DMing Absol is worse because it's not monitored.

I think this needs more review.

**Comment by Southpaw1496** [comment]
Perhaps part of the process could be to consider if it's possible to make it more obvious that Absol's commands are being triggered by a human, or maybe say something along the lines of "if you received instructions from the Absol bot, don't give it to them, give it to the person who issued the command"

**Pull request closed without merging**
