### PR TITLE
Add a favicon to all help pages

### PR DESCRIPTION
**Pull request by cheese-1024**
Add an icon of a Minecart with Hopper to all pages on minecrafthopper.net

### CODE REVIEW

**Comment by TechyDriver** [comment]
Brilliant idea, looks unpriffesional and when your internet is slow you think it's faoled to load when you see no favicon

**Comment by LordRalex** [comment]
Favicons must be an ico file and only be at most 64x64. It also should be called favicon.ico

**Comment by cheese-1024** [comment]
Welp, that shows my lack of knowledge with this stuff. I'll get that changed as soon as I can

**Comment by Southpaw1496** [comment]
Closed due to inactivity and author losing interest.

**Pull request closed without merging**
