### PR TITLE
Microsoft

### PR DESCRIPTION
**Pull request by duendwang**
* Created Microsoft privacy page
* Split "Getting Minecraft Logs" article into 5 articles--one for each type of log/report--based on feedback from other helpers.

### CODE REVIEW

**Comment by LordRalex** [comment]
I'd like to redirect the deleted page to one of the new ones, since it's a popular page. Whichever page makes the most sense would be best.

**Comment by duendwang** [comment]
How do I do that?

**Comment by duendwang** [comment]
Never mind....I found some possibilities. Probably be a few hours to a day before I can commit something working though.

**Comment by duendwang** [comment]
@LordRalex done. Needed to install a plugin in the config file if that's ok.

**Review by LordRalex — APPROVED** [review]

**Pull request merged**
