### PR TITLE
ReportBook

### PR DESCRIPTION
**Pull request by Loudbooks**
I created ReportBook a few months ago as an alternative to HJT. It provides way more information, hides more private information, and is entirely open source.

ReportBook collects OS, Processes, Memory, Swap, CPU, GPU, Hosts and Installed Apps. It automatically hides the system username but does note whether it is alphanumeric or not. (Non alphanumeric usernames are prone to causing issues)

Source and more information here: https://github.com/Loudbooks/ReportBook
Example MacOS report here: https://pastebook.dev/pastes/millie-shadow-bard-milkchocolate?inspect=true
Example Windows report here: https://pastebook.dev/pastes/poppy-rex-kokomo-milkchocolate?inspect=true
Self hosted guide here: https://mch.loudbook.dev/help/reportbook

ReportBook has been submitted to Microsoft for open source review, and has been approved.

### CODE REVIEW

**Comment by LordRalex** [comment]
"ReportBook has been submitted to Microsoft for open source review, and has been approved."

I have no idea what this means, and it really doesn't mean much to me.

**Comment by Loudbooks** [comment]
@LordRalex 

All it means is that SmartScreen will not flag it, and browsers won't flag it.

**Comment by Loudbooks** [comment]
image
Here's a screenshot of it I took a while ago until I can find the email- it was submitted here: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Loudbooks** [comment]
image
Well it appears as if submissions are only kept for 30 days- if you don't trust it I can submit it again.

**Comment by LordRalex** [comment]
That is just a scanner. It doesn't mean anything. It'd be the same as using VirusTotal.

"Microsoft security researchers analyze suspicious files to determine if they are threats, unwanted applications, or normal files. Submit files you think are malware or files that you believe have been incorrectly classified as malware".

This doesn't mean anything that you stated.

**Comment by Loudbooks** [comment]
As quoted in their response:

"We can confirm that the files submitted are now determined as clean and attempting to download or run the application should no longer show any warnings.
Due to the complexity of our backend systems, it may take up to 12 hours for the determination to be fully reflected and for the SmartScreen warnings to stop."

Is there something specific you're looking for to prove it's legitimacy? It's all open sourced, and is a fairly small project.

**Comment by LordRalex** [comment]
That is not "approved" by anything open source related. That is just saying the file isn't fine and they won't trigger warnings. That is not really "approval" or anything...  That is misleading.

Reagrdless
I also don't see enough to really make it "better" than HJT (which is also open source). It just seems like just the username is being hidden. That's it. HJT shows more information which has been useful.

**Comment by Loudbooks** [comment]
> Reagrdless I also don't see enough to really make it "better" than HJT (which is also open source). It just seems like just the username is being hidden. That's it. HJT shows more information which has been useful.

Some things that I think are notable:
- Much nicer format. It's actually readable at a glance.
- Memory usage breakdown
- An actual full hardware report


The things that I see are missing:
- Trusted zone
- Startup status

Is there anything else you feel is missing from this alternative? Whenever I ask for a HJT I go in with the intention of looking for possible malware or interfering programs. I feel as if a list of installed apps and running programs report exactly what I would be looking for.

**Comment by Loudbooks** [comment]
Fair enough. Guess it's just personal preference. Thanks for considering!

**Pull request closed without merging**
